name: Database

on:
  schedule:
    - cron: '0 18 * * MON-FRI'  #  Monday - Friday at 7 PM Madrid 
  workflow_dispatch:     

permissions:
  contents: write
jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          persist-credentials: true
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements/database_auto.txt

      - name: Update database
        run: python -m ingest.ohlcv
      
      - name: Update repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git status --porcelain | grep -q "data/ibex35.db"; then
            TODAY=$(date -u +"%Y-%m-%d")
            git add data/ibex35.db
            git commit -m "chore(db): daily OHLCV update ${TODAY}"
            git push
          else
            echo "No database changes to commit"
          fi
